import Link from 'next/link';
import { BookOpen, Clock, ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'What is JSON Schema? A Beginner Guide',
  description: 'Learn the fundamentals of JSON Schema. Understand schema validation, defining properties, arrays, required fields, and validating data structures.',
  alternates: {
    canonical: 'https://jsonformatter.revoxera.com/guides/what-is-json-schema',
  },
};

export default function JsonSchemaGuide() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-12 max-w-[900px] text-slate-300 font-light leading-relaxed">
      <div className="mb-8">
        <Link 
          href="/" 
          className="inline-flex items-center gap-2 text-xs font-black tracking-widest text-primary hover:text-white transition-colors uppercase group"
        >
          <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
          Back to Workspace
        </Link>
      </div>

      <article className="space-y-6">
        <header className="space-y-4">
          <span className="inline-block px-3 py-1 rounded-full text-[10px] font-black tracking-wider border border-primary/20 bg-primary/5 text-primary uppercase">
            Data Validation
          </span>
          <h1 className="text-3xl md:text-5xl font-black tracking-tight text-white uppercase">
            What is JSON Schema?
          </h1>
          <div className="flex items-center gap-4 text-xs opacity-50 font-bold uppercase">
            <span className="flex items-center gap-1"><BookOpen size={14} /> 5 Min Read</span>
            <span>•</span>
            <span className="flex items-center gap-1"><Clock size={14} /> Published 2026</span>
          </div>
        </header>

        <div className="glass-panel rounded-[40px] p-8 md:p-12 border border-white/10 shadow-2xl space-y-6">
          <h2 className="text-xl font-bold uppercase text-primary">Introduction to Schema Validation</h2>
          <p>
            JSON Schema is a declarative vocabulary that allows you to annotate and validate JSON documents. It provides a structured format to specify the allowed properties, data types, value boundaries, and required keys in your JSON dataset.
          </p>

          <h2 className="text-xl font-bold uppercase text-primary">A Simple Schema Example</h2>
          <p>
            Here is a basic schema describing a user profile dataset:
          </p>
          <pre className="bg-black/40 border border-white/10 p-5 rounded-3xl font-mono text-xs overflow-x-auto text-emerald-400">
{`{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "User",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "username": {
      "type": "string",
      "minLength": 3
    },
    "email": {
      "type": "string",
      "format": "email"
    }
  },
  "required": ["id", "username"]
}`}
          </pre>

          <h2 className="text-xl font-bold uppercase text-primary">Why Use Schema Assertions?</h2>
          <ul className="list-disc list-inside space-y-2 pl-2 text-xs text-slate-400">
            <li><strong className="text-white">API Security:</strong> Validates incoming HTTP payloads before querying the database, blocking malicious or malformed parameter structures.</li>
            <li><strong className="text-white">Autogenerated Docs:</strong> Provides a single source of truth that client libraries or documentation tools can render.</li>
            <li><strong className="text-white">Type Safety:</strong> Infers exact schema shapes to compile static TypeScript interfaces.</li>
          </ul>

          <div className="pt-6 border-t border-white/10 flex flex-col items-center">
            <Link 
              href="/json-validator" 
              className="px-8 py-4 rounded-2xl bg-primary text-black text-xs font-black tracking-widest transition-all shadow-[0_0_20px_rgba(56,189,248,0.3)] hover:scale-105 uppercase"
            >
              Launch JSON Validator →
            </Link>
          </div>
        </div>
      </article>
    </div>
  );
}
